### ISSUE TITLE
[ArrayPractice] Investigate arrays allocation

### ISSUE THREAD

**Issue by MLGMAG** [plotnikov01/c-practice#2]
Do this actions in scope of one program:
1. Create an array of 5 integers and print it to the terminal
2. Create an array of 5 strings and print it to the terminal.
3. Create a function, that will receive an array of 5 integers, sum them and return a result.
4. Create a function, that will receive an array of 5 integers, multiply them by x (input parameter) and return them.

**Comment by plotnikov01** [comment]
Done in [ArrayPractice] Investigate arrays allocation #5

**Comment by plotnikov01** [comment]
Done in PR #5
