### ISSUE TITLE
[Algorithms] Implementing celsius to fahrenheit calculation logic

### ISSUE THREAD

**Issue by MLGMAG** [plotnikov01/c-practice#4]
Modify the degree conversion program.
You have variables: startTemp / endTemp.
You need to convert each unit and display it in the terminal.
Do it through while.

Example:
```
Fahrenheit = 10 Celsius = 170
Fahrenheit = 11 Celsius = 176
Fahrenheit = 12 Celsius = 179
...
Fahrenheit = 80 Celsius = 1789
```

**Comment by plotnikov01** [comment]
Done in [CelsiusCalculation] Implementing celsius to fahrenheit calculation logic #8

**Comment by plotnikov01** [comment]
Done in #8
